#!/usr/bin/with-contenv sh

# launch openvpn
exec openvpn \
    --config ${OPENVPN_CONFIG_FILE} \
    --auth-user-pass ${CREDENTIALS_FILE} \
    --pull-filter ignore "DNS" \
    --dhcp-option DNS ${DNS} \
    --redirect-gateway def1 bypass-dhcp
