#!/usr/bin/with-contenv sh

CONFIG_FILE=${CONFIG_DIR}/qBittorrent/config/qBittorrent.conf
export QBT_PROFILE=${CONFIG_DIR}

# wait for VPN connection
until ifconfig | grep tun | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"; do
    sleep 0.5
done

# drop rule allowing DNS traffic outside VPN tunnel
iptables -D OUTPUT -d $(sed -n -e 's/^.*nameserver //p' /etc/resolv.conf) -p udp -m udp --dport 53 -j ACCEPT

# verify the iptables rule was dropped
if [ $? -ne 0 ]; then
    echo "ERROR: could not drop iptables rule allowing DNS traffic"
    exit 1
fi

exec s6-setuidgid ${PUID}:${PGID} qbittorrent-nox
