#!/usr/bin/with-contenv sh

CONFIG_FILE=${CONFIG_DIR}/qBittorrent/config/qBittorrent.conf
export QBT_PROFILE=${CONFIG_DIR}
TUN_DEVICE=$(ip -o link show | awk -F': ' '{print $2}' | grep tun)

# wait for VPN connection
until [ ! -z "$(ip a show ${TUN_DEVICE} up)" ]; do
    sleep 0.5
done

ip a show virbr0-nic up
# drop rule allowing DNS traffic outside VPN tunnel
iptables -D OUTPUT -p udp -d ${DNS} --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -D INPUT -p udp -s ${DNS} --sport 53 -m state --state ESTABLISHED -j ACCEPT
iptables -D OUTPUT -p tcp -d ${DNS} --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -D INPUT -p tcp -s ${DNS} --sport 53 -m state --state ESTABLISHED -j ACCEPT

# verify the iptables rule was dropped
if [ $? -ne 0 ]; then
    echo "ERROR: could not drop iptables rule allowing DNS traffic"
    exit 1
fi

exec s6-setuidgid ${PUID}:${PGID} qbittorrent-nox
