#!/usr/bin/with-contenv sh

CONFIG_FILE=${QBT_PROFILE}/qBittorrent/config/qBittorrent.conf

# wait for VPN connection
until ifconfig | grep tun | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"; do
    sleep 0.5
done

exec s6-setuidgid ${PUID}:${PGID} qbittorrent-nox
