#!/usr/bin/with-contenv sh
# shellcheck shell=sh

echo
echo
echo "############################"
echo "DEPRECATION WARNING"
echo "This image is deprecated it has important SECURITY ISSUE, see:"
echo "https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/137"
echo 
echo

# create configuration directory
mkdir -p "${CONFIG_DIR}/qBittorrent"
mkdir -p "${QBT_SAVE_PATH}"

# set permissions on configuration directory
echo "${CONFIG_DIR}/qBittorrent true ${PUID}:${PGID} 0600 0700" | fix-attrs
echo "${CONFIG_DIR}/openvpn true openvpn:openvpn 0600 0700" | fix-attrs

# set permissions on copied scripts
chmod 755 /usr/sbin/* /etc/openvpn/modify-openvpn-config.sh

echo "nameserver ${DNS}" >/etc/resolv.conf
